<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SingleFileMc.Packager</AssemblyName>
    <RootNamespace>SingleFileMc.Packager</RootNamespace>

    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <StackTraceSupport>true</StackTraceSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>