<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SingleFileMc.Packager</AssemblyName>
    <RootNamespace>SingleFileMc.Packager</RootNamespace>

    <PublishAot>true</PublishAot>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
    <StripSymbols>true</StripSymbols>
    <StackTraceSupport>true</StackTraceSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\SingleFileMc\bin\Release\net10.0\win-x64\publish\SingleFileMc.exe"
                      LogicalName="SingleFileMc.stub.bin"
                      Condition="Exists('..\SingleFileMc\bin\Release\net10.0\win-x64\publish\SingleFileMc.exe')" />
  </ItemGroup>

</Project>